### ISSUE TITLE
Disk Space Analysis

### ISSUE THREAD

**Issue by lzricardo** [lzricardo/hacker-rank#15]
```js
function segment(x, space) {
    let segments = [];

    for(let i = 0; i < space.length; i++) {
        if (x > space.length) {
            break;
        }

        segments.push(space.slice(i, x++));
    }

    let minimums = segments.map(segment => Math.min(...segment));

    return Math.max(...minimums);
}
```

**Comment by rvamsig** [comment]
@lzricardo Could you share the hacker rank page of this problem.

**Comment by lzricardo** [comment]
> @lzricardo Could you share the hacker rank page of this problem.

Hi @rvamsig , this problem did manifest for me in the company's interview by Hacker Rank platform. So, i don't have this page, but i have your description:

```
A company is performing an analysis on the computers at its main office. The computers are spaced along a single row. The analysis is performed in the following way:

1. Choose a contiguous segment of a certain number of computers, starting from the beginning of the row.
2. Analyze the available hard disk space on each of the computers.
3. Determine the minimum available disk space within this segment.

After performing these steps for the first segment, it is then repeated for the next segment, continuing this procedure until the end of the row (i.e if the segment is 4, computers 1 to 4 would be analyzed, then 2 to 5, etc...) Given this analysis procedure, find the maximum available disk space among all the minima that are found during analysis

Example
n = 3, the number of computers
space = [8, 2, 4]
x = 2, the length of analysis segments

In this array of computers, the subarrays of size 2 are [8, 2] and [2, 4]. Thus, the initial analysis returns 2 and 2 because those are the minima for the segments. Finally, the maximum of these values is 2. Therefore, the answer is 2.
```

Regards,

**Comment by kpatel4241** [comment]
def solution(x , space):
    
    occupied_space = []

    for i in range(len(space)-x+1):
        occupied_space.append(space[i:i+x])

    print(occupied_space)
    
    min_arr = []
    for i in range( len(occupied_space)):
        min_arr.append(min(occupied_space[i]))

    print(min_arr)
    
    max_ele = max(min_arr)
    return max_ele


if __name__ == "__main__":
    
    n = int(input())
    space = [int(x) for x in input().split()]
    x = int(input())

    max_val = solution(x , space)
    print(max_val)

**Comment by naman-art** [comment]
@lzricardo can you please explain the approach of your code that you wrote?

**Comment by Vuklicki** [comment]
@naman-art I can if you r still interested?

**Comment by kodedtech** [comment]
@lzricardo lzricardo thanks very much. Your solution saved me today.

**Comment by lzricardo** [comment]
> @lzricardo lzricardo thanks very much. Your solution saved me today.

You're welcome buddy ;)

**Comment by webdev0117** [comment]
> ```js
> function segment(x, space) {
>     let segments = [];
> 
>     for(let i = 0; i < space.length; i++) {
>         if (x > space.length) {
>             break;
>         }
> 
>         segments.push(space.slice(i, x++));
>     }
> 
>     let minimums = segments.map(segment => Math.min(...segment));
> 
>     return Math.max(...minimums);
> }
> ```

Do you think your solution would work for `space.length <= 10^6` ?
Your solution is actually a basic solution.

**Comment by giovanirubim** [comment]
The simplest solution is O(n*x), but there are some O(n * log x) approaches, like buffering x elements in a **balanced binary tree** or in a **minheap**. That way you can remove the oldest value, add a new value, and figure out what is the smallest, all that in O(log x) complexity.

If you are using a binary tree you can remove the oldest by removing from the tree the value that sits in the index i - x (being i the current index).
Every iteration is going to cost you a deletion, an insertion and a search. which are all O(log x).

If you are using a minheap, instead of inserting numbers you can insert nodes of a linked circular queue that follows the order that the elements were added to the heap. Also you have to store in each item of the queue in what index the item is placed in the minheap (to avoid linear searches), and keep them updated when you move elements up and down through the heap. Unlike the tree approach you don't have to pop and push, just update the value of the next element in the queue and then update their position in the heap.

By using a **minheap**, every itertaion gives you the new minimum element in the current subarray. Knowing which is the current minimum and finding the oldest both costs O(1), after finding the oldest, and replacing the value for the new value, it will cost you O(log x) to update it's position in the heap.

Both have same time complexity in best and worst case, but the method using the tree is easier if you have it implemented already, although the minheap method seems more efficient and easier if you have to implement everything from scratch

**Comment by giovanirubim** [comment]
By the way, I also had this problem in an interview, a simple variation of the basic solution was accepted. If you keep what was the previous minimum element you don't have to make a search in the current subarray all the time, only when the previous minimum leaves the subarray. Although it was accepted the worst case was still _O(n*k)_ when the array is sorted.

```javascript
function segment(x, space) {
    const end = space.length - x
    let lastMin = Infinity
    for (let i=0; i<x; ++i) {
        lastMin = Math.min(lastMin, space[i])
    }
    let maxMin = lastMin
    for (let i=1; i<end; ++i) {
        if (space[i - 1] != lastMin) {
            continue
        }
        lastMin = Infinity
        for (let j=0; j<x; ++j) {
            lastMin = Math.lastMin(lastMin, space[i + j])
        }
        maxMin = Math.max(lastMin, maxMin)
    }
    return maxMin
}
```

**Comment by giovanirubim** [comment]
The heap implementation i mentioned previously would look like this

```javascript
class ListNode {
	constructor(val, index) {
		this.val = val
		this.index = index
		this.next = null
	}
}

const heap = []
let heap_length = 0
let oldest

// Heap operations
const moveUp = (index) => {
	const item = heap[index]
	const {val} = item
	while (index !== 0) {
		const parent_index = (index - 1) >> 1
		const parent = heap[parent_index]
		if (parent.val <= val) break
		heap[index] = parent
		parent.index = index
		index = parent_index
	}
	heap[index] = item
	item.index = index
	return index
}
const moveDown = (index) => {
	const item = heap[index]
	const {val} = item
	for (;;) {
		const a_index = (index << 1) + 1
		if (a_index >= heap_length) break
		const b_index = a_index + 1
		const a = heap[a_index]
		const b = heap[b_index]
		if (b_index >= heap_length || a.val <= b.val) {
			if (a.val >= val) break
			heap[index] = a
			a.index = index
			index = a_index
		} else {
			if (b.val >= val) break
			heap[index] = b
			b.index = index
			index = b_index
		}
	}
	heap[index] = item
	item.index = index
}

// Fills the heap and creates the queue
const fillHeap = (array, x) => {
	const first = new ListNode(array[0], 0, null)
	heap.length = heap_length = x
	heap[0] = first
	let prev = first
	for (let i=1; i<x; ++i) {
		const node = new ListNode(array[i], i)
		heap[i] = node
		prev.next = node
		prev = node
		moveUp(i)
	}
	prev.next = first
	oldest = first
}

const solve = (array, x) => {
	fillHeap(array, x)
	const {length} = array
	let max = heap[0].val
	for (let i=x; i<length; ++i) {
		oldest.val = array[i]
		moveDown(moveUp(oldest.index))
		oldest = oldest.next
		max = Math.max(max, heap[0].val)
	}
	return max
}```

**Comment by giovanirubim** [comment]
The heap implementation i mentioned previously would look like this

```javascript
class ListNode {
	constructor(val, index) {
		this.val = val
		this.index = index
		this.next = null
	}
}

const heap = []
let heap_length = 0
let oldest

// Heap operations
const moveUp = (index) => {
	const item = heap[index]
	const {val} = item
	while (index !== 0) {
		const parent_index = (index - 1) >> 1
		const parent = heap[parent_index]
		if (parent.val <= val) break
		heap[index] = parent
		parent.index = index
		index = parent_index
	}
	heap[index] = item
	item.index = index
	return index
}
const moveDown = (index) => {
	const item = heap[index]
	const {val} = item
	for (;;) {
		const a_index = (index << 1) + 1
		if (a_index >= heap_length) break
		const b_index = a_index + 1
		const a = heap[a_index]
		const b = heap[b_index]
		if (b_index >= heap_length || a.val <= b.val) {
			if (a.val >= val) break
			heap[index] = a
			a.index = index
			index = a_index
		} else {
			if (b.val >= val) break
			heap[index] = b
			b.index = index
			index = b_index
		}
	}
	heap[index] = item
	item.index = index
}

// Fills the heap and creates the queue
const fillHeap = (array, x) => {
	const first = new ListNode(array[0], 0, null)
	heap.length = heap_length = x
	heap[0] = first
	let prev = first
	for (let i=1; i<x; ++i) {
		const node = new ListNode(array[i], i)
		heap[i] = node
		prev.next = node
		prev = node
		moveUp(i)
	}
	prev.next = first
	oldest = first
}

const solve = (array, x) => {
	fillHeap(array, x)
	const {length} = array
	let max = heap[0].val
	for (let i=x; i<length; ++i) {
		oldest.val = array[i]
		moveDown(moveUp(oldest.index))
		oldest = oldest.next
		max = Math.max(max, heap[0].val)
	}
	return max
}
```

**Comment by pulkitent** [comment]
Not an optimized one. Will cause TLE for some test cases.
